/* tslint:disable */
/* eslint-disable */
/**
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * The version of the OpenAPI document: 7.0.1 (UNKNOWN)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CustomAttributes
 */
export interface CustomAttributes {
  /**
   * Note:
   * This is a Primary Key.<pk/>
   * @type {string}
   * @memberof CustomAttributes
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  providerId: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  issueContainerProviderId: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  value?: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  valueId?: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  deletedAt?: string;
  /**
   *
   * @type {string}
   * @memberof CustomAttributes
   */
  scannedAt: string;
}

export function CustomAttributesFromJSON(json: any): CustomAttributes {
  return CustomAttributesFromJSONTyped(json, false);
}

export function CustomAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CustomAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    providerId: json["provider_id"],
    issueContainerProviderId: json["issue_container_provider_id"],
    type: json["type"],
    title: json["title"],
    description: !exists(json, "description") ? undefined : json["description"],
    value: !exists(json, "value") ? undefined : json["value"],
    valueId: !exists(json, "value_id") ? undefined : json["value_id"],
    createdAt: !exists(json, "created_at") ? undefined : json["created_at"],
    updatedAt: !exists(json, "updated_at") ? undefined : json["updated_at"],
    deletedAt: !exists(json, "deleted_at") ? undefined : json["deleted_at"],
    scannedAt: json["scanned_at"],
  };
}

export function CustomAttributesToJSON(value?: CustomAttributes | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    provider_id: value.providerId,
    issue_container_provider_id: value.issueContainerProviderId,
    type: value.type,
    title: value.title,
    description: value.description,
    value: value.value,
    value_id: value.valueId,
    created_at: value.createdAt,
    updated_at: value.updatedAt,
    deleted_at: value.deletedAt,
    scanned_at: value.scannedAt,
  };
}
