/* tslint:disable */
/* eslint-disable */
/**
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * The version of the OpenAPI document: 7.0.1 (UNKNOWN)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IssueCustomAttributes
 */
export interface IssueCustomAttributes {
  /**
   * Note:
   * This is a Primary Key.<pk/>
   * @type {string}
   * @memberof IssueCustomAttributes
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof IssueCustomAttributes
   */
  issueProviderId: string;
  /**
   *
   * @type {string}
   * @memberof IssueCustomAttributes
   */
  customAttributeProviderId: string;
  /**
   *
   * @type {string}
   * @memberof IssueCustomAttributes
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof IssueCustomAttributes
   */
  value?: string;
  /**
   *
   * @type {string}
   * @memberof IssueCustomAttributes
   */
  scannedAt: string;
}

export function IssueCustomAttributesFromJSON(
  json: any
): IssueCustomAttributes {
  return IssueCustomAttributesFromJSONTyped(json, false);
}

export function IssueCustomAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IssueCustomAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    issueProviderId: json["issue_provider_id"],
    customAttributeProviderId: json["custom_attribute_provider_id"],
    type: json["type"],
    value: !exists(json, "value") ? undefined : json["value"],
    scannedAt: json["scanned_at"],
  };
}

export function IssueCustomAttributesToJSON(
  value?: IssueCustomAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    issue_provider_id: value.issueProviderId,
    custom_attribute_provider_id: value.customAttributeProviderId,
    type: value.type,
    value: value.value,
    scanned_at: value.scannedAt,
  };
}
