/* tslint:disable */
/* eslint-disable */
/**
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * The version of the OpenAPI document: 7.0.1 (UNKNOWN)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Users
 */
export interface Users {
  /**
   * Note:
   * This is a Primary Key.<pk/>
   * @type {string}
   * @memberof Users
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  providerId: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  profileImgUrl?: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  scannedAt?: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  modifiedAt: string;
  /**
   *
   * @type {string}
   * @memberof Users
   */
  createdAt: string;
}

export function UsersFromJSON(json: any): Users {
  return UsersFromJSONTyped(json, false);
}

export function UsersFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Users {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    providerId: json["provider_id"],
    email: json["email"],
    firstName: !exists(json, "first_name") ? undefined : json["first_name"],
    lastName: !exists(json, "last_name") ? undefined : json["last_name"],
    profileImgUrl: !exists(json, "profile_img_url")
      ? undefined
      : json["profile_img_url"],
    scannedAt: !exists(json, "scanned_at") ? undefined : json["scanned_at"],
    modifiedAt: json["modified_at"],
    createdAt: json["created_at"],
  };
}

export function UsersToJSON(value?: Users | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    provider_id: value.providerId,
    email: value.email,
    first_name: value.firstName,
    last_name: value.lastName,
    profile_img_url: value.profileImgUrl,
    scanned_at: value.scannedAt,
    modified_at: value.modifiedAt,
    created_at: value.createdAt,
  };
}
